server:
  port: 47077
spring:
  application:
    name: minio
eureka:
  instance:
    hostname: eurekaserver
  client:
    service-url:
      defaultZone: http://eurekaserver:47073/eureka
minio:
  accessKey: admin
  secretKey: password
  endpoint: http://minio:9000
security:
  jwt:
    access: 36000000
    refresh: 2592000000
    secret: aGZiYmtiYWllYmNpZWFpZWJsZWNldWNlY2xhZWNhaWJlbGNhZWN3Q0VCV0VXSUM